<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="/css/style.css">
    <link rel="stylesheet" href="css/page.css">
</head>
<body>
<?php include_once $_SERVER['DOCUMENT_ROOT'] . '/include/menu.php'; ?>

<div class="abc"><!-- /.abc --></div>

<div class="dfg"><span>コンテンツ</span></div>

<div class="h">AAAAAAAAAAAAAAAAAAAAAAAAAAAA<br>AAAAAAAAAAAAAAAAAAAAAAAAAAAA<br>AAAAAAAAAAAAAAAAAAAAAAAAAAAA<br>AAAAAAAAAAAAAAAAAAAAAAAAAAAA<br>AAAAAAAAAAAAAAAAAAAAAAAAAAAA<br>AAAAAAAAAAAAAAAAAAAAAAAAAAAA<br>AAAAAAAAAAAAAAAAAAAAAAAAAAAA<br>AAAAAAAAAAAAAAAAAAAAAAAAAAAA<br>AAAAAAAAAAAAAAAAAAAAAAAAAAAA<br>AAAAAAAAAAAAAAAAAAAAAAAAAAAA<br>AAAAAAAAAAAAAAAAAAAAAAAAAAAA<br>AAAAAAAAAAAAAAAAAAAAAAAAAAAA<br>AAAAAAAAAAAAAAAAAAAAAAAAAAAA<br>AAAAAAAAAAAAAAAAAAAAAAAAAAAA<br>AAAAAAAAAAAAAAAAAAAAAAAAAAAA<br>AAAAAAAAAAAAAAAAAAAAAAAAAAAA<br>AAAAAAAAAAAAAAAAAAAAAAAAAAAA<br>AAAAAAAAAAAAAAAAAAAAAAAAAAAA<br>AAAAAAAAAAAAAAAAAAAAAAAAAAAA<br>AAAAAAAAAAAAAAAAAAAAAAAAAAAA<br>AAAAAAAAAAAAAAAAAAAAAAAAAAAA<br>AAAAAAAAAAAAAAAAAAAAAAAAAAAA<br>AAAAAAAAAAAAAAAAAAAAAAAAAAAA<br>AAAAAAAAAAAAAAAAAAAAAAAAAAAA<br>AAAAAAAAAAAAAAAAAAAAAAAAAAAA<br>AAAAAAAAAAAAAAAAAAAAAAAAAAAA<br>AAAAAAAAAAAAAAAAAAAAAAAAAAAA<br>AAAAAAAAAAAAAAAAAAAAAAAAAAAA<br></div><!-- /.h -->

<div class="i">
    iiiiiiiiiiiiiiiiiiiiiiiiiiii<br><br><br>iiiiiiiiiiiiiiiiiiiiiiiiiiii<br><br><br>iiiiiiiiiiiiiiiiiiiiiiiiiiii<br><br><br>iiiiiiiiiiiiiiiiiiiiiiiiiiii<br><br><br>iiiiiiiiiiiiiiiiiiiiiiiiiiii<br><br><br>iiiiiiiiiiiiiiiiiiiiiiiiiiii<br><br><br>iiiiiiiiiiiiiiiiiiiiiiiiiiii<br><br><br>iiiiiiiiiiiiiiiiiiiiiiiiiiii<br><br><br>iiiiiiiiiiiiiiiiiiiiiiiiiiii<br><br><br>iiiiiiiiiiiiiiiiiiiiiiiiiiii<br><br><br>iiiiiiiiiiiiiiiiiiiiiiiiiiii<br><br><br>iiiiiiiiiiiiiiiiiiiiiiiiiiii<br><br><br>iiiiiiiiiiiiiiiiiiiiiiiiiiii<br><br><br>iiiiiiiiiiiiiiiiiiiiiiiiiiii<br><br><br>iiiiiiiiiiiiiiiiiiiiiiiiiiii<br><br><br>iiiiiiiiiiiiiiiiiiiiiiiiiiii<br><br><br>iiiiiiiiiiiiiiiiiiiiiiiiiiii<br><br><br>iiiiiiiiiiiiiiiiiiiiiiiiiiii<br><br><br>iiiiiiiiiiiiiiiiiiiiiiiiiiii<br><br><br>iiiiiiiiiiiiiiiiiiiiiiiiiiii<br><br><br>iiiiiiiiiiiiiiiiiiiiiiiiiiii<br><br><br>iiiiiiiiiiiiiiiiiiiiiiiiiiii<br><br><br>iiiiiiiiiiiiiiiiiiiiiiiiiiii<br><br><br>iiiiiiiiiiiiiiiiiiiiiiiiiiii<br><br><br>iiiiiiiiiiiiiiiiiiiiiiiiiiii<br><br><br>
</div><!-- /.i -->
<div class="j">
    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ<br>JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ<br>JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ<br>JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ<br>JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ<br>JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ<br>JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ<br>JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ<br>
</div><!-- /.j -->
<div class="k"><img src="./curriculum.jpg" alt=""></div><!-- /.k -->

<div class="l">
    <div class="l-1">
        <p>SHANE!!</p>
        <p>SHANE!!</p>
        <p>SHANE!!</p>
        <p>SHANE!!</p>
    </div><!-- /.l-1 -->
    <div class="l-1">
        <p>SHANE!!</p>
        <p>SHANE!!</p>
        <p>SHANE!!</p>
        <p>SHANE!!</p>
    </div><!-- /.l-1 -->
    <div class="l-1">
        <p>SHANE!!</p>
        <p>SHANE!!</p>
        <p>SHANE!!</p>
        <p>SHANE!!</p>
    </div><!-- /.l-1 -->
    <div class="l-1">
        <p>SHANE!!</p>
        <p>SHANE!!</p>
        <p>SHANE!!</p>
        <p>SHANE!!</p>
    </div><!-- /.l-1 -->
</div><!-- /.l -->

<div class="m">
    <p>Text</p>
    <p>1文字目をCSSで</p>
    <p>装飾</p>
</div><!-- /.m -->

<div class="n">
    <ul class="n__list">
        <li class="n__item">
            <h2 class="n__title">AAAAAAAAAAA</h2>
            <div class="n__img"><img src="./images/1.png" alt=""></div>
        </li><!-- /.n__img -->
        <li class="n__item">
            <h2 class="n__title">AAAAAAAAAAA</h2>
            <div class="n__img"><img src="./images/1.png" alt=""></div>
        </li><!-- /.n__img -->
        <li class="n__item">
            <h2 class="n__title">AAAAAAAAAAA</h2>
            <div class="n__img"><img src="./images/1.png" alt=""></div>
        </li><!-- /.n__img -->
        <li class="n__item">
            <h2 class="n__title">AAAAAAAAAAA</h2>
            <div class="n__img"><img src="./images/1.png" alt=""></div>
        </li><!-- /.n__img -->
        <li class="n__item">
            <h2 class="n__title">AAAAAAAAAAA</h2>
            <div class="n__img"><img src="./images/1.png" alt=""></div>
        </li><!-- /.n__img -->
        <li class="n__item">
            <h2 class="n__title">AAAAAAAAAAA</h2>
            <div class="n__img"><img src="./images/1.png" alt=""></div>
        </li><!-- /.n__img -->
        <li class="n__item">
            <h2 class="n__title">AAAAAAAAAAA</h2>
            <div class="n__img"><img src="./images/1.png" alt=""></div>
        </li><!-- /.n__img -->
        <li class="n__item">
            <h2 class="n__title">AAAAAAAAAAA</h2>
            <div class="n__img"><img src="./images/1.png" alt=""></div>
        </li><!-- /.n__img -->
        <li class="n__item">
            <h2 class="n__title">AAAAAAAAAAA</h2>
            <div class="n__img"><img src="./images/1.png" alt=""></div>
        </li><!-- /.n__img -->
        <li class="n__item">
            <h2 class="n__title">AAAAAAAAAAA</h2>
            <div class="n__img"><img src="./images/1.png" alt=""></div>
        </li><!-- /.n__img -->
        <li class="n__item">
            <h2 class="n__title">AAAAAAAAAAA</h2>
            <div class="n__img"><img src="./images/1.png" alt=""></div>
        </li><!-- /.n__img -->
        <li class="n__item">
            <h2 class="n__title">AAAAAAAAAAA</h2>
            <div class="n__img"><img src="./images/1.png" alt=""></div>
        </li><!-- /.n__img -->
        <li class="n__item">
            <h2 class="n__title">AAAAAAAAAAA</h2>
            <div class="n__img"><img src="./images/1.png" alt=""></div>
        </li><!-- /.n__img -->
        <li class="n__item">
            <h2 class="n__title">AAAAAAAAAAA</h2>
            <div class="n__img"><img src="./images/1.png" alt=""></div>
        </li><!-- /.n__img -->
        <li class="n__item">
            <h2 class="n__title">AAAAAAAAAAA</h2>
            <div class="n__img"><img src="./images/1.png" alt=""></div>
        </li><!-- /.n__img -->
        <li class="n__item">
            <h2 class="n__title">AAAAAAAAAAA</h2>
            <div class="n__img"><img src="./images/1.png" alt=""></div>
        </li><!-- /.n__img -->
        <li class="n__item">
            <h2 class="n__title">AAAAAAAAAAA</h2>
            <div class="n__img"><img src="./images/1.png" alt=""></div>
        </li><!-- /.n__img -->
        <li class="n__item">
            <h2 class="n__title">AAAAAAAAAAA</h2>
            <div class="n__img"><img src="./images/1.png" alt=""></div>
        </li><!-- /.n__img -->
        <li class="n__item">
            <h2 class="n__title">AAAAAAAAAAA</h2>
            <div class="n__img"><img src="./images/1.png" alt=""></div>
        </li><!-- /.n__img -->
        <li class="n__item">
            <h2 class="n__title">AAAAAAAAAAA</h2>
            <div class="n__img"><img src="./images/1.png" alt=""></div>
        </li><!-- /.n__img -->
        <li class="n__item">
            <h2 class="n__title">AAAAAAAAAAA</h2>
            <div class="n__img"><img src="./images/1.png" alt=""></div>
        </li><!-- /.n__img -->
        <li class="n__item">
            <h2 class="n__title">AAAAAAAAAAA</h2>
            <div class="n__img"><img src="./images/1.png" alt=""></div>
        </li><!-- /.n__img -->
        <li class="n__item">
            <h2 class="n__title">AAAAAAAAAAA</h2>
            <div class="n__img"><img src="./images/1.png" alt=""></div>
        </li><!-- /.n__img -->
        <li class="n__item">
            <h2 class="n__title">AAAAAAAAAAA</h2>
            <div class="n__img"><img src="./images/1.png" alt=""></div>
        </li><!-- /.n__img -->
        <li class="n__item">
            <h2 class="n__title">AAAAAAAAAAA</h2>
            <div class="n__img"><img src="./images/1.png" alt=""></div>
        </li><!-- /.n__img -->
    </ul>

</div><!-- /.n -->

<div class="o">
    <div class="img"><img src="./images/1.png" alt=""><img src="./images/2.png" alt=""></div><!-- /.img -->
</div><!-- /.o -->

<div class="p">

</div><!-- /.p -->
    <script src="js/jquery.min.js"></script>
    <script src="js/page.js"></script>

</body>
</html>